version: "3"

services:
  app:
    image: myapp-node
    build: ./nodeapp
    restart: always
    networks:
      - web
      - default
    expose:
      - "3000"
#    volumes: 
#      - ./nodeapp:/usr/src/app
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:www.ecommerceview.ml,ecommerceview.ml"
      - "traefik.basic.port=3000"
      - "traefik.basic.protocol=http"
#      - "traefik.admin.frontend.rule=Host:sex.ecommerceviewer.ml"
#      - "traefik.admin.protocol=http"
#      - "traefik.admin.port=8080"

  events:
    image: flask_app
    build: ./flaskApp
    restart: always
    networks:
      - web
      - default
    expose:
      - "5000"
    labels:
      - "traefik.backend=flask-subdomain"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host: bug.ecommerceview.ml"
      - "traefik.enable=true"
      - "traefik.port=5000"

networks:
  web:
    external: true
